micronaut:
  application:
    name: booksPublisher
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        all:
          allowedHeaders:
            - Content-Type
          allowedMethods:
            - POST
            - PUT
            - DELETE

# Health endpoint
endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS

# Nats
nats:
  addresses:
    - nats://localhost:4222